import Head from 'next/head'
import Image from 'next/image'

import {
	ChatContainer,
	ChatHeader,
	ChatHeaderTextContainer,
	ChatInputContainer,
	ChatMessage,
	ChatMessageContainer,
	ChatSubTitle,
	ChatTitle,
} from '@/styles/pages/chat'

import { MdSend } from 'react-icons/md'

import userDefaulAvatar from 'public/assets/user.png'
import { FormEvent, useState } from 'react'

interface Message {
	sender: string
	content: string
	timestamp: string
}

export default function Chat() {
	const date = Date.now()
	const message1: Message = {
		sender: 'acarneir',
		content:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit sit deserunt praesentium nemo accusantium ratione error, quas quaerat omnis perspiciatis est quidem, earum ullam ad dolorum quis optio. Beatae, harum!',
		timestamp: (date - 10 * 60 * 1000).toLocaleString(),
	}

	const message2: Message = {
		sender: 'rfelipe-',
		content:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit sit deserunt praesentium nemo accusantium ratione error, quas quaerat omnis perspiciatis est quidem, earum ullam ad dolorum quis optio. Beatae, harum!',
		timestamp: (date + 10 * 60 * 1000).toLocaleString(),
	}

	const chat = [
		message1,
		message2,
		message2,
		message2,
		message1,
		message1,
		message1,
		message2,
		message1,
		message2,
	]
	const loggedUser = 'acarneir'

	const [input, setInput] = useState('')

	function handleSubmit(e: FormEvent<HTMLFormElement>) {
		e.preventDefault()
		console.log(e)
		console.log(input)
	}

	return (
		<>
			<Head>
				<title>Transcendence - Pong</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ChatContainer>
				<ChatHeader>
					<Image
						src={userDefaulAvatar.src}
						width={40}
						height={40}
						priority={true}
						alt="user"
					/>
					<ChatHeaderTextContainer>
						<ChatTitle>rfelipe-</ChatTitle>
						<ChatSubTitle>online</ChatSubTitle>
					</ChatHeaderTextContainer>
				</ChatHeader>
				<ChatMessageContainer>
					{chat.map((message, index) => (
						<ChatMessage
							key={index}
							isLoggedUser={message.sender === loggedUser}
						>
							{message.sender !== loggedUser && (
								<p>
									<b>{message.sender}</b>
								</p>
							)}
							<p>{message.content}</p>
						</ChatMessage>
					))}
				</ChatMessageContainer>
				<ChatInputContainer onSubmit={(e) => handleSubmit(e)}>
					<input
						type="text"
						value={input}
						onChange={(e) => setInput(e.target.value)}
					/>
					<button>
						<MdSend size={48} />
					</button>
				</ChatInputContainer>
			</ChatContainer>
		</>
	)
}
