version: '3'

services:
    db:
        image: postgres:latest
        container_name: transcendence_db
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:${DB_PORT}
        networks:
            - transcendence 

    front:
        build: ./front
        image: transcendence_front 
        container_name: transcendence_front
        restart: unless-stopped
        depends_on:
            - back
        env_file:
            - .env
        environment:
            - REACT_APP_BACK_HOST=${BACK_HOST}
            - REACT_APP_ENV=${ENV}
        ports:
            - 3000:${FRONT_PORT}
        networks:
            - transcendence 

    back:
        build: ./back
        image: transcendence_back 
        container_name: transcendence_back
        restart: unless-stopped
        depends_on:
            - db
        env_file:
            - .env
        environment:
            - DB_HOST=transcendence_db
        ports:
            - 3001:${BACK_PORT}
        networks:
            - transcendence 

networks:
    transcendence:
        driver: bridge