import Head from 'next/head'
import { ReactElement } from 'react'
import { FaGamepad } from 'react-icons/fa6'

import { HomeContainer, PlayButton } from '@/styles/pages/home'
import Layout from '@/components/layout'

export default function Home() {
	return (
		<>
			<Head>
				<title>Transcendence - Pong</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomeContainer>
				<PlayButton>
					<FaGamepad size={40} />
					Play
				</PlayButton>
			</HomeContainer>
		</>
	)
}

Home.getLayout = (page: ReactElement) => {
	return <Layout>{page}</Layout>
}
