import TwoFAInputForm from '@/components/TwoFAInputForm'
import Loading from '@/components/loading'
import { UserContext } from '@/contexts/UserContext'
import { api } from '@/services/api'
import { AuthContainer } from '@/styles/pages/auth'
import Head from 'next/head'

import { useRouter } from 'next/router'
import { useContext, useEffect, useState } from 'react'
import { toast } from 'react-toastify'

export default function Auth() {
	const { handleLogin } = useContext(UserContext)

	const router = useRouter()

	const [isLoading, setIsLoading] = useState(false)
	const [request2FA, setRequest2FA] = useState(false)

	useEffect(() => {
		async function authUser(code: string) {
			setIsLoading(true)
			try {
				const { data } = await api.post('/auth/user', { code })
				toast('Login was successful', {
					type: 'success',
					draggable: false,
				})
				const { action, user } = data
				if (action === 'authenticate') {
					setRequest2FA(true)
					setIsLoading(false)
				}
				if (action === 'logged') {
					handleLogin(user)
					router.push('/')
				}
			} catch (error) {
				toast('An error occurred during authentication', {
					type: 'error',
					draggable: false,
				})
				router.push('/login')
				setIsLoading(false)
			}
		}
		const code = router.query.code as string
		if (code) {
			authUser(code)
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [router])

	async function sendCode(twoFAcode: string) {
		setIsLoading(true)
		setRequest2FA(false)
		try {
			const res = await api.post('/checkTwoFactor', { code: twoFAcode })
			const { action, user } = res.data
			if (action === 'logged') {
				toast('Login was successful', {
					type: 'success',
					draggable: false,
				})
				handleLogin(user)
				router.push('/')
			} else {
				setIsLoading(false)
				setRequest2FA(true)
				toast('Invalid code', {
					type: 'error',
					draggable: false,
				})
			}
		} catch (error) {
			toast('An error occurred during authentication', {
				type: 'error',
				draggable: false,
			})
			// router.push('/login')
			setIsLoading(false)
			setRequest2FA(true)
		}
	}

	return (
		<>
			<Head>
				<title>Transcendence - Pong</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<AuthContainer>
				{isLoading && <Loading size={200} />}
				{request2FA && <TwoFAInputForm sendTwoFA={sendCode} />}

				{/* <button
					onClick={() => {
						toast('Authenticated', { type: 'success',draggable: false, })
					}}
				>
					Toast
				</button> */}
			</AuthContainer>
		</>
	)
}
