import { api } from '@/services/api'
import Head from 'next/head'

import { useRouter } from 'next/router'
import { useEffect } from 'react'

export default function Auth() {
	const router = useRouter()

	console.log(router.query.code)

	async function authUser() {
		const code = router.query.code

		if (code) {
			const res = await api.post('/auth/user', { code })
			console.log('res:', res)
		}
	}

	authUser()

	return (
		<>
			<Head>
				<title>Transcendence - Pong</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			auth
		</>
	)
}
