import Head from 'next/head'
import { useRouter } from 'next/router'
import Image from 'next/image'

import {
	MatchHistoryContainer,
	PageContainer,
	ProfileContainer,
	ProfileDataContainer,
	ProfileImageContainer,
	TitleContainer,
} from '@/styles/pages/profile'

import { FaUserAstronaut } from 'react-icons/fa6'
import { MdViewList } from 'react-icons/md'
import Stats from '@/components/stats'

export default function Profile() {
	const router = useRouter()
	console.log('router:', router)

	const gamesPlayed = 10
	const wins = 4
	const stats = { gamesPlayed, wins }

	const profileUser = router.query.userId ? router.query.userId : 'acarneir'
	return (
		<>
			<Head>
				<title>Transcendence - Pong</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PageContainer>
				<ProfileDataContainer>
					<ProfileContainer>
						<ProfileImageContainer>
							<Image
								src="/assets/user.png"
								width={240}
								height={240}
								alt="user"
							/>
						</ProfileImageContainer>
						<TitleContainer>
							<FaUserAstronaut size={40} />
							<h2>{profileUser}</h2>
						</TitleContainer>
					</ProfileContainer>
					<Stats stats={stats} />
				</ProfileDataContainer>
				<MatchHistoryContainer>
					<TitleContainer>
						<MdViewList size={56} />
						<h2>Match History</h2>
					</TitleContainer>
				</MatchHistoryContainer>
			</PageContainer>
		</>
	)
}
