import Head from 'next/head'
import { useRouter } from 'next/router'
import Image from 'next/image'

import {
	MatchHistoryContainer,
	PageContainer,
	ProfileContainer,
	ProfileDataContainer,
	ProfileImageContainer,
	StatsContainer,
	UserContainer,
} from '@/styles/pages/profile'

import { FaUserAstronaut } from 'react-icons/fa6'

export default function Profile() {
	const router = useRouter()
	console.log('router:', router)
	return (
		<>
			<Head>
				<title>Transcendence - Pong</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PageContainer>
				<ProfileDataContainer>
					<ProfileContainer>
						<ProfileImageContainer>
							<Image
								src="/assets/user.png"
								width={300}
								height={300}
								alt="user"
							/>
						</ProfileImageContainer>
						<UserContainer>
							<FaUserAstronaut size={40} />
							<h2>acarneir</h2>
						</UserContainer>
					</ProfileContainer>
					<StatsContainer>Stats</StatsContainer>
				</ProfileDataContainer>
				<MatchHistoryContainer>Match History</MatchHistoryContainer>
			</PageContainer>
		</>
	)
}
